#!/bin/bash

# Arte ASCII do Sauron
cat << "EOF"
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⣦⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⠞⠁⠈⢻⣿⣿⣷⣦⣄⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⠟⠁⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣷⣄⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⠟⠁⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣆
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⠀⣰⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⣰⣿⣿⣿⣿⡃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⣰⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⢠⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⣼⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⢰⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠀⢿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⡟
⠀⠀⠻⣿⣿⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀
⠀⠀⠀⠀⠙⠻⣿⣿⣿⣿⣿⣷⣦⣤⣤⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠛⠋⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
EOF

# Definir variáveis de usuário e diretório
USER=$(whoami)
GROUP=$(id -gn $USER)
PWD=$(pwd)

# Função para instalar pacotes usando o pacman
install_package() {
    package=$1
    if ! pacman -Q $package &>/dev/null; then
        sudo pacman -S --noconfirm $package
    else
        echo "$package já está instalado."
    fi
}

# Função para organizar diretórios de configuração
organize_config_dirs() {
    CONFIG_DIRS=("$HOME/.config" "$HOME/.local/share" "$HOME/.cache")

    for dir in "${CONFIG_DIRS[@]}"; do
        if [ -d "$dir" ]; then
            echo "Organizando $dir..."
            # Exemplo: mover arquivos temporários para o diretório de cache
            find "$dir" -type f -name '*.tmp' -exec mv {} "$HOME/.cache" \;
        fi
    done
}

# Atualizar o sistema
sudo pacman -Syu --noconfirm

# Instalar kitty (terminal) e Thunar (gerenciador de arquivos)
install_package kitty
install_package thunar

# Diretório de configuração do Hyperland
HYPERLAND_CONFIG_DIR="$HOME/.config/hyperland"

# Remover o diretório de configuração do Hyperland se já existir
if [ -d "$HYPERLAND_CONFIG_DIR" ]; then
    rm -rf "$HYPERLAND_CONFIG_DIR"
    echo "Diretório de configuração do Hyperland removido."
fi

# Criar diretório de configuração do Hyperland
mkdir -p "$HYPERLAND_CONFIG_DIR"
echo "Diretório de configuração do Hyperland criado."

# Criar arquivo hyperland.conf
cat <<EOL > "$HYPERLAND_CONFIG_DIR/hyperland.conf"
# HYPERLAND CONFIG FILE
# Remove autogenerated config file warning
no_autogenerated_config

# Define input devices
input "1:1:AT_Translated_Set_2_keyboard" {
    kb_layout br
}

# Define terminal emulator
exec-once kitty

# Define file manager
exec-once thunar

# Define keybindings
bind = Alt+Return, exec kitty
bind = Alt+Q, close
bind = Alt+R, reload

# Define workspaces
bind = Alt+1, workspace 1
bind = Alt+2, workspace 2
bind = Alt+3, workspace 3
bind = Alt+4, workspace 4
bind = Alt+5, workspace 5
bind = Alt+6, workspace 6
bind = Alt+7, workspace 7
bind = Alt+8, workspace 8
bind = Alt+9, workspace 9
bind = Alt+0, workspace 10

# Define window management
bind = Alt+F, fullscreen
bind = Alt+M, move
bind = Alt+S, resize

# Define layout management
bind = Alt+T, toggle floating
bind = Alt+H, split horizontal
bind = Alt+V, split vertical
bind = Alt+C, close container

# Define system controls
bind = Alt+E, exec rofi -show run
bind = Alt+L, lock
bind = Alt+P, exec poweroff
bind = Alt+B, exec reboot

# Define screenshot tool
bind = Print, exec grim -g "\$(slurp)" ~/Pictures/Screenshots/\$(date +'%Y-%m-%d_%H-%M-%S').png

# Apply configuration
include ~/.config/hyperland/keybindings.conf
include ~/.config/hyperland/layout.conf
include ~/.config/hyperland/windows.conf
EOL

echo "Configuração do Hyperland concluída."

# Diretório de configuração do Kitty
KITTY_CONFIG_DIR="$HOME/.config/kitty"

# Remover o diretório de configuração do Kitty se já existir
if [ -d "$KITTY_CONFIG_DIR" ]; then
    rm -rf "$KITTY_CONFIG_DIR"
    echo "Diretório de configuração do Kitty removido."
fi

# Criar diretório de configuração do Kitty
mkdir -p "$KITTY_CONFIG_DIR"
echo "Diretório de configuração do Kitty criado."

# Criar arquivo kitty.conf
cat <<EOL > "$KITTY_CONFIG_DIR/kitty.conf"
# KITTY CONFIG FILE

# Fonte e tamanho da fonte
font_family      FiraCode
font_size        12.0

# Mapeamentos de teclas simples
map ctrl+enter new_window
map ctrl+w close_window
map ctrl+left previous_window
map ctrl+right next_window
map ctrl+up enlarge_font
map ctrl+down shrink_font
map ctrl+equal reset_font_size

# Copiar e colar
map ctrl+c copy_to_clipboard
map
